In [ ]:
#variable
a=10
n="i am ",a," years old"
print(n)

('i am ', 10, ' years old')


In [ ]:
#adding 2 int variables
a=int(input("enter a value = "))
b=int(input("enter b value = "))
c=a+b;
print("sum is : ",c)


enter a value = 333
enter b value = 209
sum is :  542


In [ ]:
#arithmetic on 2 int variables
a=int(input("enter a value = "))
b=int(input("enter b value = "))
print("sum= ",a+b)
print("difference= ",a-b)
print("product= ",a*b)
print("quotient= ",a/b)
print("remainder= ",a%b)
print("power of a to b is = ",a**b)
print("floor division= ",a//b)

enter a value = 33
enter b value = 4
sum=  37
difference=  29
product=  132
quotient=  8.25
remainder=  1
power of a to b is =  1185921
floor division=  8


In [ ]:
#create salary from the user if the  salary is more than 50000 there is a 10% tax deduction print his final salary
a=int(input("enter salary= "))
t=a*(10/100)
if a<=0 and a>=50000:
  s=a-t
  print("your salary is=",s)
else:
  print("no deduction")



enter salary= 10000
no deduction


Arithmetic operators:
+ add
- sub
* product
/ division
// floor division
% remainder
** power

Relational operators:
< less than
> greater than
== equal to
!= not equal to
>= greater than or equal to
<= less than or equal to


In [2]:
#get the salary from the user if the salary is >=50000 apply 10% deduction , if the salary is <50000 apply 5% tax,if the salary is less than 70K apply 10% tax ,12% between 50K to 70K if salary exceeds 1 lakh print you are promoted to next level
s=int(input("enter salary= "))
if s<=50000:
  print("your salary is = ",s-(s*0.05))
elif s<=70000:
  print("your salary is=",s-(s*0.1))
elif s<=100000:
  print("your salary is = ",s-(s*0.12))
else:
  print("Your are promoted to next level..")

enter salary= 40000
your salary is =  38000.0


In [7]:
a=10
print(a<10 and a>5)
print(a<20 or a>10)



False
True


In [ ]:
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [8]:
#printing a table using for loop
n=int(input("enter number: "))
for i in range(1,13):
  print(n, "X" ,i,"=" ,n*i)

enter number: 18
18 X 1 = 18
18 X 2 = 36
18 X 3 = 54
18 X 4 = 72
18 X 5 = 90
18 X 6 = 108
18 X 7 = 126
18 X 8 = 144
18 X 9 = 162
18 X 10 = 180
18 X 11 = 198
18 X 12 = 216


In [ ]:
#using while loop
n=int(input("enter number: "))
i=1
while(i<=12):
  print(n, "X" ,i,"=" ,n*i)
  i=i+1

enter number: 25
25 X 1 = 25
25 X 2 = 50
25 X 3 = 75
25 X 4 = 100
25 X 5 = 125
25 X 6 = 150
25 X 7 = 175
25 X 8 = 200
25 X 9 = 225
25 X 10 = 250
25 X 11 = 275
25 X 12 = 300


In [ ]:
#CREATE A  HETEROGENEOUS LIST
l=[1,"kill",89,"chat",9.1,True]
for i in l:
   print(i)

1
kill
89
chat
9.1
True


In [ ]:
#MUTABLE
l.append("append")#adding element at back of the list
print(l)

[1, 'kill', 89, 'chat', 9.1, True, 'append']


In [ ]:
#insertion
l.insert(4,"inserted")  #listname.insert(index,element)
print(l)

[1, 'chat', 1, 'inserted', 9.1, 'append']


In [ ]:
l2=["python","concatenated"]
print(l+l2)# + or .insert will work for concatnating 2 lists
l1=[1,3,"pink"]

#extend
#list1.extend(list2)
l1.extend(l)  #l1=l1+l2
print(l1)

[1, 'kill', 89, 'chat', 'inserted', 9.1, True, 'append', 'python', 'concatenated']
[1, 3, 'pink', 1, 'kill', 89, 'chat', 'inserted', 9.1, True, 'append']


In [ ]:
#delete using pop deletes if u know the index
l.pop(2)    #listname.pop(index)
print(l)


[1, 'kill', 'chat', 'inserted', 9.1, True, 'append']


In [ ]:
#delete using remove (by giving element to be deleted as input)
l.remove("kill")   #listname.remove(element)
print(l)

['chat', 'inserted', 9.1, 'append']


In [ ]:
#clear clears the whole list
l1.clear()   #listname.clear()
print(l1)

[]


In [ ]:
#create a list of 10 integer elements print their squares save these squares ina new list
l1=[12,22,34,45,56,62,76,88,91,10]
l3=[]
for i in l1:
  l3.append(i**2)
print(l3)



[144, 484, 1156, 2025, 3136, 3844, 5776, 7744, 8281, 100]


In [ ]:
#list comprehension
#newlist = [output for]
l1=[12,22,34,45,56,62,76,88,91,10 ]
l3=[i*i for i in l1 ]
print(l3)


[144, 484, 1156, 2025, 3136, 3844, 5776, 7744, 8281, 100]


In [ ]:
#checking a condition in a list comprehension
#newlist = [output for if cond]
l1=[12,22,34,45,56,62,76,88,91,10 ]
l3=[i*i for i in l1 if i>50]
print(l3)

[3136, 3844, 5776, 7744, 8281]


In [ ]:
#LC
#newlist = [(st of if) if (cond) else (st of else) for]
l1=[12,56,22,34,62,76,88,91,42,10 ]
l3=[i*i if i>50 else 'X' for i in l1 ]
print(l3)

['X', 3136, 'X', 'X', 3844, 5776, 7744, 8281, 'X', 'X']


In [ ]:
#take the salary from the user if salary<50K 10% tax otherwise 15%

l=[int(input("enter salary"))]
res=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in l ]
print(res)

enter salary700000
[595000.0]


In [ ]:
l4=[30000,508876,23456]
res=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in l4 ]
print(res)


[27000.0, 432544.6, 21110.4]


In [ ]:
#create DICTIONARY
#dict_name = {key1:val1,key2:val2,...}
dict1 = {'mentor':'jwalitha','mentor':'likhitha',35:'ramya',37:'lavanya',58:'danush'}
print(dict1)


{'mentor': 'likhitha', 35: 'ramya', 37: 'lavanya', 58: 'danush'}


In [9]:
dict1 = {'mentor':'jwalitha','mentor':'likhitha',35:'ramya',37:'lavanya',58:'danush'}
print(dict1.keys())
print(dict1.values())

dict_keys(['mentor', 35, 37, 58])
dict_values(['likhitha', 'ramya', 'lavanya', 'danush'])


In [ ]:
dict1 = {'mentor':'jwalitha','mentor':'likhitha',35:'ramya',37:'lavanya',58:'danush'}
print(dict1[37])  #to get a particular value

lavanya


In [ ]:
#nested dictionary
dict3={"dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print("year= ",dict3["details"]["year"])
print("section= ",dict3["details"]["sec"])
print("strength is = ",dict3["details"]["count"])

year=  II
section=  D
strength is =  71


In [ ]:
#create a dictionary from 2 lists
Id=[34,56,78,39,100]
name=['joe','suji','rohini','shankar','mani']
new_zip=(zip(Id,name))
for i in new_zip:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'rohini')
(39, 'shankar')
(100, 'mani')


In [ ]:
#creating a dictionary from zip
Id=[34,56,78,39,100]
name=['joe','suji','rohini','shankar','mani']
print(dict(zip(Id,name)))   #using dict

{34: 'joe', 56: 'suji', 78: 'rohini', 39: 'shankar', 100: 'mani'}


In [ ]:
#NUMPY
import numpy as np
A = np.array([1,2,3,4])     #1d array
print(A)
print(A.ndim)
print(A.shape)

[1 2 3 4]
1
(4,)


In [ ]:
B = np.array([[1,2,3],[4,5,6],
              [8,9,10],[11,12,13]])     #2d array
#elements in each row =columns
print(B)
print(B.ndim)
print(B.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]]
2
(4, 3)


In [ ]:
c = np.array([[[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]]])   #3d array
print(c)
print(c.ndim)
print(c.shape)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]]]
3
(2, 3, 3)


In [ ]:
A = np.ones((4,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.ones((3,4,2))     #groups rows columns
print(A)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
A = np.zeros((4,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
A = np.eye(4)     #to implement identity matrix
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.arange(1,10)
print(A)

[1 2 3 4 5 6 7 8 9]


In [ ]:
A = np.arange(1,10,2)   #start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using array function between 1 to 1000
A = np.arange(8,1001,8)
print(A)



[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A = np.linspace(40,80,5)   #upperlimit,lowerlimit,no.of spaces(seperates with equal difference)
# line spaces : spliting a range into n numbers with common differences
print(A)

[40. 50. 60. 70. 80.]


In [ ]:
#1)study tuples and sets(day_1 :Work) 2)documentation 3)qr code task send