In [ ]:
a=[8,6,7,12,3,5]
b=sorted(a)
print(b)

[3, 5, 6, 7, 8, 12]


In [ ]:
a=[8,23,4,5,6,12]
a.sort()
print(a)

[4, 5, 6, 8, 12, 23]


In [ ]:
a=(12,334,1,5,6,5)
b=sorted(a)
print(a)
print(b)

(12, 334, 1, 5, 6, 5)
[1, 5, 5, 6, 12, 334]


In [ ]:
#arange
import numpy as np
A = np.arange(1,13)
print(A)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#reshape
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#linspace
import numpy as np
A = np.linspace(1,13,8).reshape(4,2)
print(A)

[[ 1.          2.71428571]
 [ 4.42857143  6.14285714]
 [ 7.85714286  9.57142857]
 [11.28571429 13.        ]]


In [ ]:
#RESHAPE
B = np.array([12,34,54,6,65,56,78,32]).reshape(2,2,2)   #changes needs saving in another variable
print(B)

[[[12 34]
  [54  6]]

 [[65 56]
  [78 32]]]


In [ ]:
#RESIZE
B = np.array([12,34,54,6,65,56,78,32])
B.resize(2,2,2)   #changes the shape of original array
print(B)

[[[12 34]
  [54  6]]

 [[65 56]
  [78 32]]]


In [2]:
A = np.array([34,56,78,90])   #list will throw an error while arrays iterate themselves
B = np.array([7,5,6,3])
c=A-B
print(c)

NameError: name 'np' is not defined

In [ ]:
upto now array creation and size manipulation topics completed

ARRAY OPERATIONS

In [ ]:
A = np.array([34,56,78,90])
B = np.array([7,5,6,3])
print(A.max())
print(A.min())

90
34


In [ ]:
A = np.array([34,56,78,90])
B = np.array([7,5,6,3])
print(A+B)

[41 61 84 93]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,5,6,3]).reshape(2,2)
print(A)
print("--------------------------------------")
print(B)
print("--------------------------------------")
C=A*B
print(C)
print("--------------------------------------")


[[34 56]
 [78 90]]
--------------------------------------
[[7 5]
 [6 3]]
--------------------------------------
[[238 280]
 [468 270]]
--------------------------------------


In [ ]:
#MATRIX MULTIPLICATION
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,5,6,3]).reshape(2,2)
print(A)
print("--------------------------------------")
print(B)
print("--------------------------------------")
C=A@B
print(C)
print("--------------------------------------")

[[34 56]
 [78 90]]
--------------------------------------
[[7 5]
 [6 3]]
--------------------------------------
[[ 574  338]
 [1086  660]]
--------------------------------------


In [ ]:
#MATRIX MULTIPLICATION
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,5,6,3]).reshape(2,2)
print(A)
print("--------------------------------------")
print(B)
print("--------------------------------------")
C=A.dot(B)
print(C)
print("--------------------------------------")

[[34 56]
 [78 90]]
--------------------------------------
[[7 5]
 [6 3]]
--------------------------------------
[[ 574  338]
 [1086  660]]
--------------------------------------


In [ ]:
A =np.array([34.2,3.5,6.4,78.1])
B = np.array([32.4,98,5.4,3.4]) #max,min only accepts numeric data types int and float
print(A.max())
print(B.min())

78.1
3.4


In [ ]:
A = np.array([34,56,90,2,3,56,67,43,44,78,54,10]).reshape(4,3)
print(A)
print("-------------------------------")
print(A.max(axis=0))      #axis=0 for column wise
print("---------------------------------")
print(A.max(axis=1))      #axis=1 for row wise
print("---------------------------------")
print(A.min(axis=0))
print("---------------------------------")
print(A.min(axis=1))

[[34 56 90]
 [ 2  3 56]
 [67 43 44]
 [78 54 10]]
-------------------------------
[78 56 90]
---------------------------------
[90 56 67 78]
---------------------------------
[ 2  3 10]
---------------------------------
[34  2 43 10]


In [ ]:
#joining arrays
#vertical stack:placing top of another box
#horizontal stack:placing side by side in a single array
A =np.array([34,3,6,78])
B = np.array([32,98,5,3])
print(A)
print("-------------------------")
print(B)
print("After vertical stacking the arrays!")
print(np.vstack((A,B)))

[34  3  6 78]
-------------------------
[32 98  5  3]
After vertical stacking the arrays!
[[34  3  6 78]
 [32 98  5  3]]


In [ ]:
A =np.array([34,3,6,78])
B = np.array([32,98,5,3])
print(A)
print("-------------------------")
print(B)
print("After horizontal stacking the arrays!")
print(np.hstack((A,B)))

[34  3  6 78]
-------------------------
[32 98  5  3]
After vertical stacking the arrays!
[34  3  6 78 32 98  5  3]


In [ ]:
A =np.array([34,3,6,78])
B = np.array([32,98,5,3])
print(A)
print("-------------------------")
print(B)
print("After vertical stacking the arrays!")
print(np.stack((A,B),axis=0))

[34  3  6 78]
-------------------------
[32 98  5  3]
After vertical stacking the arrays!
[[34 32]
 [ 3 98]
 [ 6  5]
 [78  3]]


In [ ]:
A =np.array([34,3,6,78])
B = np.array([32,98,5,3])
print(A)
print("-------------------------")
print(B)
print("After vertical stacking the arrays!")
print(np.stack((A,B),axis=1))

[34  3  6 78]
-------------------------
[32 98  5  3]
After vertical stacking the arrays!
[[34 32]
 [ 3 98]
 [ 6  5]
 [78  3]]


In [ ]:
A = np.arange(30).reshape(2,3,5)
print(A)
print("after dstack")
print(np.dstack(A))
#no. of rows--> no.of groups
#no. of col in every group --> no.of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A = np.arange(18).reshape(6,3)
print(A)
print("After  vertically splitting")    #splits into given no. of arrays
np.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A = np.arange(18).reshape(6,3)
print(A)
print("After splitting vertically")    #cuts into given no. of arrays from given indexes
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
splitting arrays
A = np.arange(18).reshape(3,6)
print(A)
print("After  horizontally splitting")    #splits into given no. of arrays
np.hsplit(A,3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After  horizontally splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
#splitting arrays
A = np.arange(18).reshape(3,6)
print(A)
print("After splitting horizontally")    #cuts into given no. of arrays from given indexes
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting horizontally


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(2,4)
print(A)
print(A.argmax())

[[12 44  5  5]
 [ 6  7 65  4]]
6


In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(2,4)
print(A)
print(A.argmax(axis=0))

[[12 44  5  5]
 [ 6  7 65  4]]
[0 0 1 0]


In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(2,4)
print(A)
print(A.argmax(axis=1))

[[12 44  5  5]
 [ 6  7 65  4]]
[1 2]


In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(2,4)         #position [0 1 2 3]
print(A)                                                          [0 1 2 3]
print(A.argmin())

[[12 44  5  5]
 [ 6  7 65  4]]
7


In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(4,2)                           #positions [0 1]
                                                                          #[0 1]
print(A)
print(A.argmin(axis=0))

[[12 44]
 [ 5  5]
 [ 6  7]
 [65  4]]
[1 3]


In [ ]:
A = np.array([12,44,5,5,6,7,65,4]).reshape(2,4)
print(A)
print(A.argmax(axis=1))

[[12 44  5  5]
 [ 6  7 65  4]]
[1 2]


**STATISTICS**

1.   all the formulas should be in documentation



In [ ]:
#mean,median,std,var
A = np.array([12,34,25,66,71,88])
print("Mean = ",np.mean(A))
print("Median = ",np.median(A))
print("Variance = ",np.var(A))
print("Standard Deviation = ",np.std(A))

Mean =  49.333333333333336
Median =  50.0
Variance =  743.888888888889
Standard Deviation =  27.274326552435515


TRIGNOMETRY

In [ ]:
A = np.pi
print(A)  #radians

3.141592653589793


In [ ]:
np.rad2deg(A)       #radians to degree

180.0

In [ ]:
B= np.array([np.pi/4,np.pi/3,np.pi/2,np.pi/1])
print(B)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(B))

[1833.46494442 5614.98639228  286.47889757  171.88733854]


In [ ]:
#degree to radiance
C = np.array([0,30,45,60,90,180])
D = np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
       -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
       -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        1.33869021])

In [ ]:
np.arcsin(1)      #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)    #cos^-1

0.0

In [ ]:
np.arctan(1)      #tan^-1

0.7853981633974483

In [ ]:
a = 3
b = 4
print(np.hypot(a,b))    #hypotenuse

5.0


SEARCHING
in an array

In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A==90))

(array([0, 5]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))

(array([0, 4, 5]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A>25))

(array([0, 2, 4, 5]),)


search sorted


In [ ]:
A = np.array([90,3,45,22,34,80,21])
print(np.searchsorted(A,45))    #it gives index as output after performing sorting           #outputs the index of a sorted element
#3,21,22,34,45,80,90

5


LINEAR ALGEBRA AND UNIVERSAL FUNCTION

In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.divide(A,B))
print(np.mod(A,B))
print(np.divmod(A,B))

[12 28 70 17 22]
[ 0 20 50  7 14]
[1.  6.  6.  2.4 4.5]
[0 0 0 2 2]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [ ]:
A = np.array([6,24,60,12,18])
print(np.sort(A))


[ 6 12 18 24 60]


In [ ]:
A = np.array([6,24,60,12,18])         #second element - first element
np.diff(A)

array([ 18,  36, -48,   6])

SET FUNCTIONS

In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 18 24 60]


In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


ROUNDING

In [ ]:
A = np.trunc([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
A = np.fix([-3.1666,3.6667])
print(A)

[-3.  3.]


In [ ]:
A = np.around([-3.1666,4])
print(A)

[-3.  4.]


In [ ]:
A = np.floor([-3.1666,3.6667])
print(A)

[-4.  3.]


In [ ]:
A = np.ceil([-3.1666,3.1])
print(A)

[-3.  4.]


In [ ]:
B = np.array([10,23,405,55,90])
print(np.trunc(B))
print(np.fix(B))
print(np.floor(B))
print(np.ceil(B))
print(np.around(B))



[ 10.  23. 405.  55.  90.]
[ 10.  23. 405.  55.  90.]
[ 10.  23. 405.  55.  90.]
[ 10.  23. 405.  55.  90.]
[ 10  23 405  55  90]


MORE FUNCTIONS

In [ ]:
A = np.array([3,4,16,19,10])
print(np.cumsum(A))

[ 3  7 23 42 52]


In [ ]:
A = np.array([3,4,16,19,10])
print(np.cumprod(A))

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56))
print(np.gcd(445,655))

952
5


In [ ]:
ar = np.array([45,65,30])
print(np.lcm.reduce(ar))

1170


In [ ]:
ar = np.array([45,65,30])
print(np.gcd.reduce(ar))

5


In [ ]:
a = np.array([[[1,2],[3,4]]])
print(np.linalg.inv(a))

[[[-2.   1. ]
  [ 1.5 -0.5]]]


RANDOM

In [ ]:
from numpy import random as rd    #syntax

In [ ]:
A = rd.rand()     #n #default limit  0 to 0.99
print(A)

0.006864974064642038


In [ ]:
A = rd.rand(10)
a = rd.rand(4)
print(A)
print(a)

[0.78316075 0.90445216 0.80260809 0.11865685 0.31438832 0.03272335
 0.65279789 0.78568886 0.68077985 0.54908837]
[0.83726205 0.2422132  0.4150081  0.85075149]


In [ ]:
A = rd.randint(4)  #randint(limit)==> limit 0,1,2,3
print(A)

1


In [ ]:
A = rd.randint(50,size=6)
print(A)

[38 20 49  1  3  1]


In [ ]:
A = rd.randint(50,size=(2,3))
print(A)

[[11 32 37]
 [ 5 33 42]]


JOINS

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(np.inner(A,B))

32


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])

print(np.cross(A,B))